export const products = [
    
      {
        image: "/Product Images/Frontimg1.jpg",
        hoverImage: "/Product Images/Backimg1.jpg",
        description: "Trim Dress",
        category: "New Arrival",
        originalPrice: "145.00",
        discountPrice: "87.00",
      },
      {
        image: "/Product Images/Frontimg2.jpg",
        hoverImage: "/Product Images/Backimg2.jpg",
        description: "Belted Dress",
        category: "New Arrival",
        originalPrice: "185.00",
        discountPrice: "111.00",
      },
      {
        image: "/Product Images/Frontimg3.jpg",
        hoverImage: "/Product Images/Backimg3.jpg",
        description: "Fitted Dress",
        category: "New Arrival",
        originalPrice: "174.00",
        discountPrice: "104.40",
      },
      {
        image: "/Product Images/Frontimg4.jpg",
        hoverImage: "/Product Images/Backimg4.jpg",
        description: "Belted Top",
        category: "New Arrival",
        originalPrice: "98.00",
        discountPrice: "49.00",
      },
      {
        image: "/Product Images/Frontimg5.jpg",
        hoverImage: "/Product Images/Backimg5.jpg",
        description: "Wait Dress",
        category: "New Arrival",
        originalPrice: "230.00",
        discountPrice: "184.00",
      },
      {
        image: "/Product Images/Frontimg6.jpg",
        hoverImage: "/Product Images/Backimg6.jpg",
        description: "Crop Top",
        category: "New Arrival",
        originalPrice: "121.00",
        discountPrice: "72.60",
      },
      {
        image: "/Product Images/Frontimg7.jpg",
        hoverImage: "/Product Images/Backimg7.jpg",
        description: "Sleevless Dress",
        category: "New Arrival",
        originalPrice: "290.00",
        discountPrice: "261.00",
      },
      {
        image: "/Product Images/Frontimg8.jpg",
        hoverImage: "/Product Images/Backimg8.jpg",
        description: "V-Neck Dress",
        category: "New Arrival",
        originalPrice: "315.00",
        discountPrice: "94.50",
      },

      {
        image: "/Product Images/Frontimg9.jpg",
        hoverImage: "/Product Images/Backimg9.jpg",
        description: "Arm Chair",
        category: "Featured",
        originalPrice: "250.00",
        discountPrice: "200.00",
      },
      {
        image: "/Product Images/Frontimg10.jpg",
        hoverImage: "/Product Images/Backimg10.jpg",
        description: "Oak Finish Chair",
        category: "Featured",
        originalPrice: "290.00",
        discountPrice: "275.50",
      },
      {
        image: "/Product Images/Frontimg11.jpg",
        hoverImage: "/Product Images/Backimg11.jpg",
        description: "Wooden Chair",
        category: "Featured",
        originalPrice: "400.00",
        discountPrice: "160.00",
      },
      {
        image: "/Product Images/Frontimg12.jpg",
        hoverImage: "/Product Images/Backimg12.jpg",
        description: "Metal Table Lamp",
        category: "Featured",
        originalPrice: "300.00",
        discountPrice: "240.00",
      },
      {
        image: "/Product Images/Frontimg13.jpg",
        hoverImage: "/Product Images/Backimg13.jpg",
        description: "Wood End Table",
        category: "Featured",
        originalPrice: "500.00",
        discountPrice: "400.00",
      },
      {
        image: "/Product Images/Frontimg14.jpg",
        hoverImage: "/Product Images/Backimg14.jpg",
        description: "Lounge Chair",
        category: "Featured",
        originalPrice: "420.00",
        discountPrice: "378.00",
      },
      {
        image: "/Product Images/Frontimg15.jpg",
        hoverImage: "/Product Images/Backimg15.jpg",
        description: "Rocking Chair",
        category: "Featured",
        originalPrice: "560.00",
        discountPrice: "448.00",
      },
      {
        image: "/Product Images/Frontimg16.jpg",
        hoverImage: "/Product Images/Backimg16.jpg",
        description: "Barrel Chair",
        category: "Featured",
        originalPrice: "610.00",
        discountPrice: "457.50",
      },

      {
        image: "/Product Images/Frontimg1.jpg",
        hoverImage: "/Product Images/Backimg1.jpg",
        description: "Trim Dress",
        category: "Special",
        originalPrice: "145.00",
        discountPrice: "87.00",
      },
      {
        image: "/Product Images/Frontimg2.jpg",
        hoverImage: "/Product Images/Backimg2.jpg",
        description: "Belted Dress",
        category: "Special",
        originalPrice: "185.00",
        discountPrice: "111.00",
      },
      {
        image: "/Product Images/Frontimg3.jpg",
        hoverImage: "/Product Images/Backimg3.jpg",
        description: "Fitted Dress",
        category: "Special",
        originalPrice: "174.00",
        discountPrice: "104.40",
      },
      {
        image: "/Product Images/Frontimg4.jpg",
        hoverImage: "/Product Images/Backimg4.jpg",
        description: "Belted Top",
        category: "Special",
        originalPrice: "98.00",
        discountPrice: "49.00",
      },
      {
        image: "/Product Images/Frontimg5.jpg",
        hoverImage: "/Product Images/Backimg5.jpg",
        description: "Wait Dress",
        category: "Special",
        originalPrice: "230.00",
        discountPrice: "184.00",
      },
      {
        image: "/Product Images/Frontimg6.jpg",
        hoverImage: "/Product Images/Backimg6.jpg",
        description: "Crop Top",
        category: "Special",
        originalPrice: "121.00",
        discountPrice: "72.60",
      },
      {
        image: "/Product Images/Frontimg7.jpg",
        hoverImage: "/Product Images/Backimg7.jpg",
        description: "Sleevless Dress",
        category: "Special",
        originalPrice: "290.00",
        discountPrice: "261.00",
      },
      {
        image: "/Product Images/Frontimg8.jpg",
        hoverImage: "/Product Images/Backimg8.jpg",
        description: "V-Neck Dress",
        category: "Special",
        originalPrice: "315.00",
        discountPrice: "94.50",
      },
  ];

